name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer update --ansi --no-progress --prefer-dist --no-interaction
      - run: composer run lint

  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        include:
          - php: '8.3'
            os: 'macos-latest'
          - php: '8.3'
            os: 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer update --ansi --no-progress --prefer-dist --no-interaction
      - run: composer run test:cover
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
